# Generated by Django 5.2.18 on 2026-10-09 06:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=20)),
                ('function', models.CharField(blank=True, max_length=120)),
                ('date', models.DateField()),
                ('guests', models.PositiveIntegerField()),
                ('food', models.CharField(blank=True, max_length=30)),
                ('delivery', models.CharField(blank=True, max_length=10, verbose_name='Door delivery')),
                ('venue', models.CharField(blank=True, max_length=250, verbose_name='Venue / address')),
                ('notes', models.TextField(blank=True)),
                ('send_to', models.CharField(blank=True, max_length=20, verbose_name='Sent to number')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('link', 'Video link')], default='photo', editable=False, max_length=10)),
                ('file', models.FileField(blank=True, upload_to='gallery/')),
                ('link', models.URLField(blank=True, verbose_name='Video link (YouTube / Facebook / Instagram)')),
                ('caption', models.CharField(blank=True, max_length=140)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gallery photo / video',
                'verbose_name_plural': 'Gallery photos / videos',
                'ordering': ['-created', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80)),
                ('place', models.CharField(blank=True, max_length=80, verbose_name='Town or village')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('text', models.TextField(max_length=1500)),
                ('approved', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created', '-id'],
            },
        ),
    ]
